### ISSUE TITLE
Concatenation of flows

### ISSUE THREAD

**Issue by control-toolbox** [control-toolbox/Flows.jl#5]
See [Issue 78](https://github.com/control-toolbox/OptimalControl.jl/issues/78).

* [x] encapsuler la sortie de la fonction `Flow` dans un type structuré pour ensuite pouvoir faire de la composition de flot, de l'affichage, etc.
* [x] tester si on peut concaténer un flot autonome avec un non autonome.
* [ ] utiliser la détection d'évènements pour switcher d'un flot à l'autre.
* [ ] ajouter la possibilité de donner une fonction de commutation plutôt qu'un temps pour la concaténation de flots. Voir si cela a du sens car on veut peut-être plutôt quelque chose comme ça 
```math
\begin{align*}
\dot{x}(t) &= f_1(t, x(t)) ~\text{si}~ \Phi(t, x(t)) < 0 \\
\dot{x}(t) &= f_2(t, x(t)) ~\text{si}~ \Phi(t, x(t)) > 0
\end{align*}
```

**Remarque.** Il faudrait ajouter la possibilité de donner une grille sur laquelle on retourne la solution pour de l'affichage, etc.

**Comment by ocots** [comment]
~~On peut ajouter la possibilité de passer des fonctions en arguments pour faire des calculs le long du flot, par exemple pour la fonction de tir, le contrôle, etc. Ce sera pratique avec de la composition il me semble.~~

**Comment by ocots** [comment]
* [x] Sinon, je pense qu'il faut utiliser `F.rhs!` si `t < t_switch`. Ce sera mieux lors des restarts après `tstops`. Pour l'instant j'utilise le paramètre `tstops` et non pas de la détection d'événements.
