### ISSUE TITLE
Use of StaticArrays

### ISSUE THREAD

**Issue by control-toolbox** [control-toolbox/Flows.jl#7]
Voir si on utilise des [StaticArrays](https://github.com/JuliaArrays/StaticArrays.jl) pour améliorer les performances.

**Comment by ocots** [comment]
Faire du benchmarking pour illustration.

**Comment by jbcaillau** [comment]
exact. r. veltz recommande pour les perfs, à tester.

**Comment by ocots** [comment]
Pour l'instant, d'après mes tests sur [HamiltonianFlows](https://github.com/control-toolbox/HamiltonianFlows.jl/tree/bench/bench) ça ralentit l'exécution !

**Comment by ocots** [comment]
* [x] ajouter un log des benchs dans [HamiltianFlows](https://github.com/control-toolbox/HamiltonianFlows.jl/tree/bench/bench)

**Comment by ocots** [comment]
Le log est ici : https://github.com/control-toolbox/HamiltonianFlows.jl/tree/main/bench/v0.1.0
